# ~/.config/starship.toml

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """\
    ${directory}\
    ${git_branch}\
    ${git_state}\
    ${git_status}→ \
    """

[git_branch]
format = "$branch(:$remote_branch)($style) "
only_attached = false
