# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """\
    ${directory}\
    ${jobs}\
    ${git_branch}\
    ${git_state}\
    ${git_status}→ \
    """

[git_branch]
format = "$branch(:$remote_branch)($style) "
only_attached = false

[jobs]
symbol = "+"
number_threshold = 1

[directory]
truncation_length = 2
truncate_to_repo = false
#truncation_length = 4
# Catppuccin 'lavender'
style = "bold lavender"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green) ❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# palette tables should be last in the config ⚓️
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
