# ~/.config/starship.toml

#[git_branch]
#format='[$symbol$branch(:$remote_branch)]($style) '

format = """$directory→ """

#vicmd_symbol = "[V](bold green) "
# ← →

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
#add_newline = false
