# ~/.config/starship.toml

#[git_branch]
#format='[[$branch(:$remote_branch)]]($style) '

#format = """$directory$git_branch→ """

#vicmd_symbol = "[V](bold green) "
# ← →

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
#add_newline = false

#format = """\
    #${username}\
    #${hostname}\
    #${directory}\
    #${git_branch}\
    #${git_state}\
    #${git_status}\
    #${python}\
    #${rust}\
    #${cmd_duration}\
    #${line_break}\
    #${jobs}\
    #${shell}\
    #${custom.nix}\
    #${character}\
    #"""


format = """\
    ${directory}\
    ${git_branch}\
    ${git_state}\
    ${git_status}→ \
    """

[git_branch]
format = "$branch(:$remote_branch)($style) "
only_attached = false

#command_timeout = 50

#format = """
#$jobs\
#$character\
#"""

#[jobs]
#format = "[\\[$number\\]]($style) "
#style = "242"
#number_threshold = 1
#symbol_threshold = 2
