# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """\
    ${directory}\
    ${jobs}\
    ${git_branch}\
    ${git_state}\
    ${git_status}→ \
    """

[git_branch]
format = "$branch(:$remote_branch)($style) "
only_attached = false

[jobs]
symbol = "+"
number_threshold = 1

[directory]
truncation_length = 2
truncate_to_repo = false
